/**
 * Build a printable DPP PDF from generated questions using pdf-lib.
 * Two pages: (1) questions only, (2) answer key + explanations.
 */
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import type { DPPQuestion } from "./dpp-generator";

export type DPPPdfMeta = {
  batchName: string;
  chapter: string;
  subject: string;
  brand?: string; // e.g. "codmaayush"
};

export async function buildDPPPdf(questions: DPPQuestion[], meta: DPPPdfMeta): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const italic = await pdf.embedFont(StandardFonts.HelveticaOblique);

  const PAGE_W = 595;   // A4 width
  const PAGE_H = 842;   // A4 height
  const MARGIN = 50;
  const CONTENT_W = PAGE_W - MARGIN * 2;

  const brand = meta.brand ?? "codmaayush";
  const blue = rgb(0.14, 0.39, 0.92);
  const dark = rgb(0.06, 0.09, 0.16);
  const gray = rgb(0.45, 0.5, 0.6);
  const green = rgb(0.05, 0.6, 0.35);

  // ─── Helpers ────────────────────────────────────────────────
  function newPage() {
    const page = pdf.addPage([PAGE_W, PAGE_H]);
    let y = PAGE_H - MARGIN;

    // Header bar
    page.drawRectangle({ x: 0, y: PAGE_H - 30, width: PAGE_W, height: 30, color: blue });
    page.drawText(`${brand.toUpperCase()} · Daily Practice Problem`, {
      x: MARGIN, y: PAGE_H - 20, size: 11, font: bold, color: rgb(1, 1, 1),
    });
    // Footer
    page.drawText(`Generated by ${brand} · Instagram: @${brand}`, {
      x: MARGIN, y: 20, size: 8, font: italic, color: gray,
    });
    y = PAGE_H - 60;
    return { page, y };
  }

  /** Wrap text to fit width. */
  function wrap(text: string, maxWidth: number, size: number, f = font): string[] {
    const words = text.split(/\s+/);
    const lines: string[] = [];
    let line = "";
    for (const w of words) {
      const candidate = line ? line + " " + w : w;
      const width = f.widthOfTextAtSize(candidate, size);
      if (width > maxWidth && line) { lines.push(line); line = w; }
      else line = candidate;
    }
    if (line) lines.push(line);
    return lines;
  }

  /** Sanitize any characters pdf-lib's WinAnsi encoding can't render. */
  function s(text: string): string {
    return text
      .replace(/[\u2018\u2019]/g, "'")
      .replace(/[\u201C\u201D]/g, '"')
      .replace(/[\u2013\u2014]/g, "-")
      .replace(/\u2022/g, "*")
      .replace(/[^\x00-\xff]/g, "?"); // fallback for unicode chars (Greek letters etc.)
  }

  // ─── PAGE 1+: Questions ────────────────────────────────────────
  let { page, y } = newPage();

  // Title block
  page.drawText(s(meta.batchName), { x: MARGIN, y, size: 18, font: bold, color: dark });
  y -= 22;
  page.drawText(s(`${meta.subject} · ${meta.chapter}`), { x: MARGIN, y, size: 12, font, color: gray });
  y -= 8;
  page.drawLine({ start: { x: MARGIN, y }, end: { x: PAGE_W - MARGIN, y }, thickness: 1, color: blue });
  y -= 20;

  page.drawText(`Total questions: ${questions.length}    Total marks: ${questions.reduce((s, q) => s + q.marks, 0)}`, {
    x: MARGIN, y, size: 10, font: italic, color: gray,
  });
  y -= 25;

  for (let i = 0; i < questions.length; i++) {
    const q = questions[i];
    const qLabel = `Q${i + 1}.  `;
    const qLines = wrap(s(q.question), CONTENT_W - 30, 11, font);
    const lineHeight = 15;

    // Estimate space needed
    const needed = qLines.length * lineHeight + (q.type === "mcq" ? q.options.length * lineHeight + 10 : 30) + 20;
    if (y - needed < 60) { const np = newPage(); page = np.page; y = np.y; }

    // Q number + type badge
    page.drawText(qLabel, { x: MARGIN, y, size: 11, font: bold, color: blue });
    const badge = q.type === "mcq" ? "[MCQ]" : "[Integer]";
    page.drawText(badge, { x: PAGE_W - MARGIN - font.widthOfTextAtSize(badge, 9), y, size: 9, font: italic, color: gray });

    // Question text
    for (const ln of qLines) {
      page.drawText(ln, { x: MARGIN + 25, y, size: 11, font, color: dark });
      y -= lineHeight;
    }
    y -= 5;

    if (q.type === "mcq") {
      const letters = ["A", "B", "C", "D"];
      for (let oi = 0; oi < q.options.length; oi++) {
        const optText = `(${letters[oi]})  ${s(q.options[oi])}`;
        const optLines = wrap(optText, CONTENT_W - 40, 10, font);
        for (const ln of optLines) {
          if (y < 60) { const np = newPage(); page = np.page; y = np.y; }
          page.drawText(ln, { x: MARGIN + 35, y, size: 10, font, color: dark });
          y -= 13;
        }
      }
    } else {
      page.drawText("Answer: ______________", { x: MARGIN + 25, y, size: 10, font, color: gray });
      y -= 15;
    }
    y -= 10;
  }

  // ─── PAGE N: Answer Key & Solutions ───────────────────────────
  const key = pdf.addPage([PAGE_W, PAGE_H]);
  key.drawRectangle({ x: 0, y: PAGE_H - 30, width: PAGE_W, height: 30, color: green });
  key.drawText("ANSWER KEY & SOLUTIONS", { x: MARGIN, y: PAGE_H - 20, size: 11, font: bold, color: rgb(1, 1, 1) });
  let ky = PAGE_H - 60;

  key.drawText(s(`${meta.batchName} — ${meta.chapter}`), { x: MARGIN, y: ky, size: 14, font: bold, color: dark });
  ky -= 20;
  key.drawLine({ start: { x: MARGIN, y: ky }, end: { x: PAGE_W - MARGIN, y: ky }, thickness: 0.5, color: gray });
  ky -= 20;

  let solPage = key;
  for (let i = 0; i < questions.length; i++) {
    const q = questions[i];
    const ansStr = q.type === "mcq"
      ? `Answer: (${["A","B","C","D"][q.correctIndex]}) ${s(q.options[q.correctIndex])}`
      : `Answer: ${q.answer}`;

    const expLines = wrap(s(q.explanation), CONTENT_W - 30, 10, font);
    const needed = 30 + expLines.length * 13 + 15;
    if (ky - needed < 60) {
      solPage = pdf.addPage([PAGE_W, PAGE_H]);
      solPage.drawRectangle({ x: 0, y: PAGE_H - 30, width: PAGE_W, height: 30, color: green });
      solPage.drawText("ANSWER KEY (continued)", { x: MARGIN, y: PAGE_H - 20, size: 11, font: bold, color: rgb(1, 1, 1) });
      ky = PAGE_H - 60;
    }

    solPage.drawText(`Q${i + 1}.`, { x: MARGIN, y: ky, size: 11, font: bold, color: blue });
    solPage.drawText(ansStr, { x: MARGIN + 30, y: ky, size: 10, font: bold, color: green });
    ky -= 15;

    for (const ln of expLines) {
      if (ky < 60) {
        solPage = pdf.addPage([PAGE_W, PAGE_H]); ky = PAGE_H - 60;
      }
      solPage.drawText(ln, { x: MARGIN + 30, y: ky, size: 10, font, color: dark });
      ky -= 13;
    }
    ky -= 8;
  }

  solPage.drawText(`Generated by ${brand} · Instagram: @${brand}`, {
    x: MARGIN, y: 20, size: 8, font: italic, color: gray,
  });

  return await pdf.save();
}
